-- data A = Zero | One | Two
-- 
-- plus One Zero = One
-- plus One One = Two
-- 
-- main = plus One (Zero ? One)
main = 1 + (0 ? 1)





------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> 1
--> 2
