xor :: Bool -> Bool -> Bool
xor True True = False
xor True False = True
xor False True = True
xor False False = False
main :: Bool
main = cond (x=:=(False?True)) (xor x x) where x free

------ CORRECT ANSWER BELOW GENERATED BY cytest.py using pakcs ------
--> False
--> False
