f [] = []
f (x:xs) = let y = x:y
               z = (y++y)
            in take x z ++ f xs

main = f [3,5]

------ CORRECT ANSWER BELOW GENERATED BY cytest.py using pakcs ------
--> [3,3,3,5,5,5,5,5]
