data Color = R | G | B

next R = G
next G = B
next B = R

f 0 a = case (next a) of R -> 0
f 1 a = case (next a) of G -> 1

main = f (0 ? 1) x where x free

------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> 0
--> 1
