-- Example from "Declarative programmin with function patterns," page 11.
-- Note: the linearization is handled by CMC without need to generate implicit
-- =:= commands.  This is because ICurry directly expresses sharing relationships.

k0 x = 0
pair x y = (x,y)
f (pair (k0 x) x) = 99
main = f (0, failed)


------ CORRECT ANSWER BELOW GENERATED BY cytest.py using pakcs ------
--> 99
--$?-> 0
