zero = 0
one = 1
two = 2
goal = [
    ((one + two) - zero) * two
  , 15 `div` 4
  , 15 `div` (-4)
  , (-15) `div` 4
  , (-15) `div` (-4)
  , 15 `mod` 4
  , 15 `mod` (-4)
  , (-15) `mod` 4
  , (-15) `mod` (-4)
  , 15 `quot` 4
  , 15 `quot` (-4)
  , (-15) `quot` 4
  , (-15) `quot` (-4)
  , 15 `rem` 4
  , 15 `rem` (-4)
  , (-15) `rem` 4
  , (-15) `rem` (-4)
  ]

main = goal

------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> [6,3,(-4),(-4),3,3,(-1),1,(-3),3,(-3),(-3),3,3,3,(-3),(-3)]
