-- KICS2 --
-- The classical function pattern:
last (_++[e]) = e

testlast n = last (map (const False) [1..n] ++ [True])

main = testlast 100000


------ CORRECT ANSWER BELOW GENERATED BY cytest.py using kics2 ------
--> True
--$?-> 0
