build [] [] = 0
build [] (_:_) = 1
build (_:_) [] = 2
build (_:_) (_:_) = 3

main = (build [] [], build [] [1], build [1] [], build [1] [1])

------ CORRECT ANSWER BELOW GENERATED BY cytest.py using pakcs ------
--> (0,1,2,3)
--$?-> 0
