data B = B Int Int
data C = C Int Int Int
data A = A B C
sum (A (B a b) (C c d e)) = a + b + c + d + e
main = sum (A (B 1 2) (C 1 2 3))




------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> 9
