-- This program requires the N function to be looped.  For a node
-- x(x_0, ..., x_n), if N(x_i) becomes a choice or failure, then
-- N(x) must be reapplied to handle it.

pairs [] = []
pairs (_:[]) = []
pairs (a:a':as) = (a,a') : pairs as

main = pairs [1,2?3,4]

------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> [(1,2)]
--> [(1,3)]
