problem1 x y 
  = if (y<0) then
       case x of a:b -> if (a>0) then [a] else (
                            if (y>0) then [] else problem1 b y)
                 []  -> if (y>0) then [y] else []
    else []

main = (problem1 [2] (-1), problem1 [0] 0, problem1 [0,1] (-1))


------ CORRECT ANSWER BELOW GENERATED BY cytest.py using pakcs ------
--> ([2],[],[1])
--$?-> 0
