-- KICS2 --

insert x [] = [x]
insert x (y:ys) = x:y:ys ? y : (insert x ys)

perm [] = []
perm (x:xs) = insert x (perm xs)

sorted :: [Int] -> [Int]
sorted []       = []
sorted [x]      = [x]
sorted (x:y:ys) | x <= y = x : sorted (y:ys)

psort xs = sorted (perm xs)

sortmain n = psort (2:[n,n-1 .. 3]++[1])

-- main = sortmain 15
main = sortmain 3


------ CORRECT ANSWER BELOW GENERATED BY cytest.py using kics2 ------
--> [1,2,3]
--$?-> 0
