data T = A | B T | C T T

main = fcase unknown of
    A -> "A"
    B A -> "(B A)"
    B (B (B _))-> "(B (B (B ...)))"
    B (B _)-> "(B (B ...))"
    B _ -> "(B ...)"
    C _ _ -> "(C ...)"

------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> "(B (B (B ...)))"
--> "(B (B ...))"
--> "(B ...)"
--> "(B A)"
--> "(C ...)"
--> "A"
