-- KICS2 --
test x = let z free
             y = (x,x)
             w = (z,z,y)
         in  z &> w 

main = test True

------ CORRECT ANSWER BELOW GENERATED BY cytest.py using kics2 ------
--> (Success,Success,(True,True))
--$?-> 0
