-- Example from "Declarative Programming with Function Patterns", Antoy & Hanus

from x = x : from (x+1)
f x | x =:= from 0 = 99
goal1 = let x free in f x
goal2 = let x free in (f x, 99)
goal3 = let x free in (f x, f x)
-- main = goal3


------ CORRECT ANSWER BELOW GENERATED BY cytest.py using pakcs ------

