sign0if a = if (a<0) then -1 else (if (a>0) then 1 else 0)
sign1if c a = if c then -1 else (if (a>0) then 1 else 0)
sign2if c a = if (a<0) then -1 else (if c then 1 else 0)
sign3if c1 c2 = if c1 then -1 else (if c2 then 1 else 0)
sign0case a = case (a<0) of True -> -1; False -> (case (a>0) of True -> 1; False -> 0)
sign1case c a = case c of True -> -1; False -> (case (a>0) of True -> 1; False -> 0)
sign2case c a = case (a<0) of True -> -1; False -> (case c of True -> 1; False -> 0)
sign3case c1 c2 = case c1 of True -> -1; False -> (case c2 of True -> 1; False -> 0)

nested (a:b:t) = if (a/=b) then (a,b):nested t else nested t

main = [
    sign0if 2, sign1if False 2, sign2if True 2, sign3if False True
  , sign0case 2, sign1case False 2, sign2case True 2, sign3case False True
  ]




------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> [1,1,1,1,1,1,1,1]
