data color = Red | Green | Blue

pick_l = Red
pick_l = Green
pick_l = Blue

pick_r = Red ? Green ? Blue

main = (pick_l,pick_r)

------ CORRECT ANSWER BELOW GENERATED BY cytest.py ------
--> (Blue,Blue)
--> (Blue,Green)
--> (Blue,Red)
--> (Green,Blue)
--> (Green,Green)
--> (Green,Red)
--> (Red,Blue)
--> (Red,Green)
--> (Red,Red)
